"""Report generation from recorded findings + engagement metadata.

Produces a client-ready Markdown report and an HTML export. Confirmed findings (those
the verification engine reproduced) are separated from tentative ones, each carries its
reproduction record and proof-of-concept, and secret-looking values are redacted so the
report is safe to hand over.
"""

from __future__ import annotations

import datetime as _dt
import html
import re

from .config import Engagement
from .findings import FindingStore

_SEV_LABEL = {"critical": "Critical", "high": "High", "medium": "Medium",
              "low": "Low", "info": "Informational"}

# Rough CWE -> CVSS-ish base severity band, for a quick at-a-glance column.
_SEV_SCORE = {"critical": "9.0-10.0", "high": "7.0-8.9", "medium": "4.0-6.9",
              "low": "0.1-3.9", "info": "-"}

_REDACTIONS = [
    (re.compile(r"(?i)(authorization:\s*bearer\s+)[A-Za-z0-9._-]+"), r"\1[REDACTED]"),
    (re.compile(r"(?i)(password\"?\s*[:=]\s*\"?)[^\s\"&]+"), r"\1[REDACTED]"),
    (re.compile(r"(?i)(api[_-]?key\"?\s*[:=]\s*\"?)[^\s\"&]+"), r"\1[REDACTED]"),
    (re.compile(r"(?i)(token\"?\s*[:=]\s*\"?)[A-Za-z0-9._-]{12,}"), r"\1[REDACTED]"),
    (re.compile(r"\beyJ[A-Za-z0-9._-]{20,}"), "[REDACTED-JWT]"),  # JWTs
]


def redact(text: str) -> str:
    if not text:
        return text
    for pattern, repl in _REDACTIONS:
        text = pattern.sub(repl, text)
    return text


def _exec_summary(findings) -> tuple[dict, int, int]:
    counts: dict[str, int] = {}
    confirmed = tentative = 0
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
        if f.confidence == "confirmed":
            confirmed += 1
        else:
            tentative += 1
    return counts, confirmed, tentative


def build_report(engagement: Engagement, store: FindingStore, requests_used: int = 0) -> str:
    findings = store.all()
    counts, confirmed, tentative = _exec_summary(findings)

    L: list[str] = []
    L.append(f"# Penetration Test Report — {engagement.name}")
    L.append("")
    L.append(f"**Client:** {engagement.client}  ")
    L.append(f"**Authorized by:** {engagement.authorized_by} (ref: {engagement.ticket})  ")
    L.append(f"**Test window:** {engagement.starts} to {engagement.ends}  ")
    L.append(f"**Report generated:** {_dt.date.today().isoformat()}  ")
    L.append(f"**In-scope hosts:** {', '.join(engagement.allowed_hosts)}")
    L.append("")

    L.append("## Executive summary")
    L.append("")
    L.append(f"The assessment recorded **{len(findings)} finding(s)** — "
             f"**{confirmed} confirmed** (reproduced) and **{tentative} tentative**.")
    L.append("")
    if counts:
        L.append("| Severity | Count | CVSS band |")
        L.append("| --- | --- | --- |")
        for sev in ("critical", "high", "medium", "low", "info"):
            if counts.get(sev):
                L.append(f"| {_SEV_LABEL[sev]} | {counts[sev]} | {_SEV_SCORE[sev]} |")
        L.append("")

    for group, title in (("confirmed", "Confirmed findings"), ("tentative", "Tentative findings")):
        subset = [f for f in findings if (f.confidence == "confirmed") == (group == "confirmed")]
        if not subset:
            continue
        L.append(f"## {title}")
        for i, f in enumerate(subset, 1):
            L.append("")
            L.append(f"### {i}. {f.title} — {_SEV_LABEL.get(f.severity, f.severity)}")
            L.append("")
            meta = f"**Target:** {f.target} · **Confidence:** {f.confidence}"
            if f.cwe:
                meta += f" · **{f.cwe}**"
            if f.trials:
                meta += f" · **Reproduced {f.reproductions}/{f.trials}**"
            L.append(meta)
            L.append("")
            L.append(f"**Summary:** {f.summary}")
            L.append("")
            if f.poc:
                L.append("**Proof of concept:**")
                L.append("")
                L.append("```")
                L.append(redact(f.poc))
                L.append("```")
                L.append("")
            if f.evidence:
                L.append("**Evidence:**")
                L.append("")
                L.append("```")
                L.append(redact(f.evidence))
                L.append("```")
                L.append("")
            if f.recommendation:
                L.append(f"**Recommendation:** {f.recommendation}")
                L.append("")

    L.append("---")
    L.append("*Generated by an authorized red-team agent. Confirmed findings were "
             "reproduced by an automated verification check; see the audit log for the "
             "full activity record.*")
    return "\n".join(L)


def build_html_report(engagement: Engagement, store: FindingStore, requests_used: int = 0) -> str:
    """Minimal, self-contained HTML rendering of the same content."""
    findings = store.all()
    counts, confirmed, tentative = _exec_summary(findings)
    rows = "".join(
        f"<tr><td>{_SEV_LABEL[s]}</td><td>{counts[s]}</td><td>{_SEV_SCORE[s]}</td></tr>"
        for s in ("critical", "high", "medium", "low", "info") if counts.get(s)
    )
    items = []
    for f in findings:
        badge = "confirmed" if f.confidence == "confirmed" else "tentative"
        repro = f" · reproduced {f.reproductions}/{f.trials}" if f.trials else ""
        items.append(
            f"<div class='f {badge}'><h3>{html.escape(f.title)} "
            f"<span class='sev {f.severity}'>{_SEV_LABEL.get(f.severity, f.severity)}</span></h3>"
            f"<p class='meta'>{html.escape(f.target)} · {f.confidence}"
            f"{' · ' + html.escape(f.cwe) if f.cwe else ''}{repro}</p>"
            f"<p>{html.escape(f.summary)}</p>"
            + (f"<pre>{html.escape(redact(f.poc))}</pre>" if f.poc else "")
            + (f"<p class='rec'><b>Recommendation:</b> {html.escape(f.recommendation)}</p>"
               if f.recommendation else "")
            + "</div>"
        )
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>Pentest Report — {html.escape(engagement.name)}</title>
<style>
 body{{font:15px/1.5 system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}}
 h1{{border-bottom:2px solid #333;padding-bottom:.3rem}}
 table{{border-collapse:collapse;margin:1rem 0}} td,th{{border:1px solid #ccc;padding:.3rem .6rem}}
 .f{{border-left:4px solid #999;padding:.5rem 1rem;margin:1rem 0;background:#fafafa}}
 .f.confirmed{{border-left-color:#c0392b}} .f.tentative{{border-left-color:#e0a800}}
 .sev{{font-size:.7rem;padding:.1rem .4rem;border-radius:3px;color:#fff;background:#666}}
 .sev.critical{{background:#7b241c}} .sev.high{{background:#c0392b}} .sev.medium{{background:#d68910}}
 .meta{{color:#666;font-size:.85rem}} pre{{background:#eee;padding:.6rem;overflow:auto}}
</style></head><body>
<h1>Penetration Test Report — {html.escape(engagement.name)}</h1>
<p><b>Client:</b> {html.escape(engagement.client)} · <b>Authorized by:</b>
 {html.escape(engagement.authorized_by)} (ref: {html.escape(engagement.ticket)})<br>
 <b>Window:</b> {engagement.starts} to {engagement.ends} · <b>Generated:</b> {_dt.date.today()}</p>
<h2>Executive summary</h2>
<p>{len(findings)} finding(s): <b>{confirmed} confirmed</b>, {tentative} tentative.</p>
<table><tr><th>Severity</th><th>Count</th><th>CVSS band</th></tr>{rows}</table>
<h2>Findings</h2>
{''.join(items) or '<p>No findings recorded.</p>'}
<hr><p style="color:#888;font-size:.8rem">Confirmed findings were reproduced by an automated
 verification check. Secrets redacted. See the audit log for the full activity record.</p>
</body></html>"""
